#!/usr/bin/env python3
"""Generate exact historical unary query methods from pinned chain schemas.

Requires an authenticated gh CLI for the Injective source repositories. Runtime
requests never use reflection or perform source discovery. Run from repo root:
  python3 tools/generate-history-methods.py
"""
import concurrent.futures
import re
import subprocess
from pathlib import Path

# Dependency revisions come from this chain revision's go.mod; module selection
# comes from injective-chain/app/app.go at the same revision.
CORE = "2e3b4f9a9ef3d2c5c0758dd2e3a2b23c35458190"
COSMOS = "3361beeef240618d6dd70ca35259880bb73e7cda"  # v0.50.14-inj.11
IBC = "dbee2d797b8a34179ece0082eebe96bfe023de1e"  # v8.7.0-inj.4
WASM = "e0e9de04a62d8405a85abd6e8ef3fdad9dd5461e"  # v0.53.3-inj.3

COSMOS_MODULES = ["auth/v1beta1", "authz/v1beta1", "bank/v1beta1", "consensus/v1",
 "distribution/v1beta1", "evidence/v1beta1", "feegrant/v1beta1", "gov/v1", "gov/v1beta1",
 "mint/v1beta1", "params/v1beta1", "slashing/v1beta1", "staking/v1beta1", "upgrade/v1beta1"]
INJECTIVE_MODULES = ["auction/v1beta1", "downtimedetector/v1beta1", "erc20/v1beta1", "evm/v1",
 "exchange/v1beta1", "exchange/v2", "insurance/v1beta1", "oracle/v1beta1", "peggy/v1",
 "permissions/v1beta1", "tokenfactory/v1beta1", "txfees/v1beta1", "wasmx/v1"]
IBC_MODULES = ["applications/fee/v1", "applications/interchain_accounts/host/v1",
 "applications/transfer/v1", "core/channel/v1", "core/client/v1", "core/connection/v1"]
# These body-height reads use Service instead of Query. Never admit every
# Service method: cosmos.tx Service also contains BroadcastTx.
SERVICE_READS = {
 "/cosmos.base.tendermint.v1beta1.Service/GetBlockByHeight",
 "/cosmos.base.tendermint.v1beta1.Service/GetValidatorSetByHeight",
 "/cosmos.base.tendermint.v1beta1.Service/ABCIQuery",
 "/cosmos.tx.v1beta1.Service/GetBlockWithTxs",
}
SOURCES = (
 [("InjectiveLabs/injective-core", CORE, f"proto/injective/{m}/query.proto") for m in INJECTIVE_MODULES]
 + [("InjectiveLabs/cosmos-sdk", COSMOS, f"proto/cosmos/{m}/query.proto") for m in COSMOS_MODULES]
 + [("InjectiveLabs/cosmos-sdk", COSMOS, "proto/cosmos/base/tendermint/v1beta1/query.proto"),
    ("InjectiveLabs/cosmos-sdk", COSMOS, "proto/cosmos/tx/v1beta1/service.proto")]
 + [("InjectiveLabs/ibc-go", IBC, f"proto/ibc/{m}/query.proto") for m in IBC_MODULES]
 + [("InjectiveLabs/wasmd", WASM, "proto/cosmwasm/wasm/v1/query.proto")]
)


def parse_methods(source):
    # Mask strings and comments before balancing service braces. Text inside
    # options/comments must never create a fake service or RPC declaration.
    source = re.sub(r'//[^\n]*|/\*[\s\S]*?\*/|"(?:\\.|[^"\\])*"', ' ', source)
    package = re.search(r'\bpackage\s+([\w.]+)\s*;', source)
    if not package:
        raise ValueError("missing protobuf package")
    methods = []
    for service in re.finditer(r'\bservice\s+(\w+)\s*\{', source):
        depth, end = 1, service.end()
        while depth and end < len(source):
            depth += (source[end] == '{') - (source[end] == '}')
            end += 1
        if depth:
            raise ValueError("unclosed service body")
        for rpc in re.finditer(r'\brpc\s+(\w+)\s*\(\s*(stream\s+)?[\w.]+\s*\)\s*returns\s*\(\s*(stream\s+)?[\w.]+\s*\)', source[service.end():end-1]):
            name = f"/{package.group(1)}.{service.group(1)}/{rpc.group(1)}"
            if (service.group(1) == "Query" or name in SERVICE_READS) and not (rpc.group(2) or rpc.group(3)):
                methods.append(name)
    return methods


def fetch(item):
    repo, revision, path = item
    source = subprocess.check_output(["gh", "api", "-H", "Accept: application/vnd.github.raw+json",
        f"repos/{repo}/contents/{path}?ref={revision}"], text=True)
    methods = parse_methods(source)
    if not methods:
        raise ValueError(f"no eligible unary reads in {repo}/{path}")
    return item, methods


def main():
    with concurrent.futures.ThreadPoolExecutor(max_workers=6) as pool:
        entries = sorted(pool.map(fetch, SOURCES))
    methods = {method for _, group in entries for method in group}
    if not SERVICE_READS <= methods:
        raise ValueError("body-height Service schema changed")
    lines = ["// Code generated by tools/generate-history-methods.py; DO NOT EDIT.",
        "// Source versions match Injective core " + CORE + ".",
        "// Cosmos: v0.50.14-inj.11; IBC: v8.7.0-inj.4; Wasmd: v0.53.3-inj.3.",
        "// Modules are selected from injective-chain/app/app.go; Query RPCs are",
        "// read-only module contracts. Streaming methods, Msg services, unknown",
        "// future methods, and off-chain indexer services are excluded.",
        "package cosmos_grpc", "", "var historicalUnaryMethods = map[string]struct{}{"]
    seen = set()
    for (repo, revision, path), group in entries:
        lines.append(f"\t// https://github.com/{repo}/blob/{revision}/{path}")
        for method in sorted(group):
            if method not in seen:
                lines.append(f'\t"{method}": {{}},')
                seen.add(method)
    lines += ["}", "", "// Retry only schema-verified unary reads; names alone cannot establish",
        "// whether a future Query method streams or has side effects.",
        "func historicalReadMethod(method string) bool {",
        "\t_, ok := historicalUnaryMethods[method]", "\treturn ok", "}", ""]
    output = Path(__file__).resolve().parents[1] / "internal/server/cosmos_grpc/history_methods.go"
    output.write_text("\n".join(lines))
    subprocess.run(["gofmt", "-w", str(output)], check=True)
    print(f"Generated {len(methods)} exact unary query methods from {len(entries)} pinned schemas")


if __name__ == "__main__":
    main()
